### ISSUE TITLE
IDEA plugin can not work

### ISSUE THREAD

**Issue by ImmortalFan** [phodal/shire#174]
**Describe the bug**
install the plugin shire in idea，but can not work

**Additional context**
java.lang.IllegalStateException: Shire language not found
	at com.phodal.shirecore.ui.input.ShireInput.createShireFile(ShireInput.kt:150)
	at com.phodal.shirecore.ui.input.ShireInput.access$createShireFile(ShireInput.kt:30)
	at com.phodal.shirecore.ui.input.ShireInput$1.onSubmit(ShireInput.kt:53)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at jdk.proxy42/jdk.proxy42.$Proxy367.onSubmit(Unknown Source)
	at com.phodal.shirecore.ui.input.ShireInputTextField$3.afterActionPerformed(ShireInputTextField.kt:74)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:768)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:712)
	at com.intellij.util.messages.impl.MessageBusImplKt.executeOrAddToQueue(MessageBusImpl.kt:533)
	at com.intellij.util.messages.impl.ToDirectChildrenMessagePublisher.publish$intellij_platform_core(CompositeMessageBus.kt:318)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:481)
	at jdk.proxy2/jdk.proxy2.$Proxy353.afterActionPerformed(Unknown Source)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.fireAfterActionPerformed(ActionManagerImpl.kt:1085)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1185)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.kt:396)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner(IdeKeyEventDispatcher.kt:848)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.access$doPerformActionInner(IdeKeyEventDispatcher.kt:1)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.kt:577)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.kt:512)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.kt:451)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.kt:444)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.kt:306)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:606)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$22(IdeEventQueue.kt:565)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:117)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by phodal** [comment]
对应的 IDEA 版本是多少？社区版还是？

**Comment by ImmortalFan** [comment]
> 对应的 IDEA 版本是多少？社区版还是？

IDEA 版本是 2024.3.1.1，不是社区版本，这个是只支持社区版吗？

**Comment by phodal** [comment]
重启过吗

**Comment by ImmortalFan** [comment]
> 重启过吗

IDEA 重启过了，电脑也重启过了，插件也重新安装过，.shire 文件识别不了，idea 的文件类型也没有 shire 类型的

**Comment by phodal** [comment]
按道理，你版本和我一样，应该是可以的。你是从 JetBrains 插件商店下载的，还是？

**Comment by ImmortalFan** [comment]
> 按道理，你版本和我一样，应该是可以的。你是从 JetBrains 插件商店下载的，还是？
> 
> <img alt="image" width="849" src="https://private-user-images.githubusercontent.com/472311/399462027-29637c1a-7a2e-4075-b48f-491a9032e578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NDY5MjMsIm5iZiI6MTczNTY0NjYyMywicGF0aCI6Ii80NzIzMTEvMzk5NDYyMDI3LTI5NjM3YzFhLTdhMmUtNDA3NS1iNDhmLTQ5MWE5MDMyZTU3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQxMjAzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTg0NTE5OTcyZjY5ZTNiMmI3NDg0MjVjZTE5NjUyYzYwMTFhOGI0NzMwNTVhY2I1ODc0NjVlZDVhZWM2ZmJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o43Eq23t4e7W_4ZP6hZVQrO_dvqhbY7hgjPk2qD1L0s">
> 可以看看是不是有依赖？

我是在 idea 里边的插件商店安装的，你说的依赖 是什么意思？

**Comment by phodal** [comment]
我重新试了一下没问题，会不会是有进度度，没等安装完成 ？

<img width="709" alt="image" src="https://github.com/user-attachments/assets/7ca6a5ca-015d-41c4-8151-c033eae020b3" />

**Comment by ImmortalFan** [comment]
> 我重新试了一下没问题，会不会是有进度度，没等安装完成 ？
> 
> <img alt="image" width="709" src="https://private-user-images.githubusercontent.com/472311/399473803-7ca6a5ca-015d-41c4-8151-c033eae020b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NDk2MTQsIm5iZiI6MTczNTY0OTMxNCwicGF0aCI6Ii80NzIzMTEvMzk5NDczODAzLTdjYTZhNWNhLTAxNWQtNDFjNC04MTUxLWMwMzNlYWUwMjBiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQxMjQ4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGJjNmM3ZDBhMDRkMTU1MTEyMmNkYmQ0YjdmNWZjODkyZDE5NGVjMmM5YzI3OWZiMWY3ZTZmYmI1NDM5ODMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Nq36haXdpGqtMyf13gJiLfUAO5s0-ZbNX_XeiVfrkcU">

应该是 IDEA 的问题，我用另外一个电脑测试过，没问题，不知道是和其他插件有冲突还是 IDEA 的设置有冲突

**Comment by phodal** [comment]
应该不可能，Java 虚拟机，试试从 Relase 下载一份到本地安装：https://github.com/phodal/shire/releases

**Comment by ImmortalFan** [comment]
> 应该不可能，Java 虚拟机，试试从 Relase 下载一份到本地安装：https://github.com/phodal/shire/releases

release 的之前我也试过了，也是不行，但是我机器上的rider客户端没问题，其他的就不行了，我装了7个不同客户端，都试过了，只有rider和clion客户端没问题，再排查是不是什么设置导致不生效

**Comment by phodal** [comment]
可以看看这一页：https://plugins.jetbrains.com/plugin/24549-shire--ai-coding-agent-language/versions

上面会显示兼容问题

**Comment by ImmortalFan** [comment]
> https://plugins.jetbrains.com/plugin/24549-shire--ai-coding-agent-language/versions

[Shell Script](https://plugins.jetbrains.com/plugin/13122-shell-script)，难道是因为我禁用了这个插件吗

**Comment by phodal** [comment]
那估计是了……

**Comment by ImmortalFan** [comment]
> 那估计是了……

的确是因为 shell script 插件的原因，之前使用了BaseSupport 插件
